"""espacio de trabajo del editor web

Revision ID: 1060445ba064
Revises: b4e286913775
Create Date: 2026-09-05 13:07:08.652192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1060445ba064'
down_revision: Union[str, Sequence[str], None] = 'b4e286913775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espacio_trabajo',
    sa.Column('participacion_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('archivos', sa.Text(), nullable=False),
    sa.Column('bytes_total', sa.Integer(), nullable=False),
    sa.Column('momento_guardado', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participacion_id'], ['participacion.id'], ),
    sa.PrimaryKeyConstraint('participacion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('espacio_trabajo')
    # ### end Alembic commands ###
