"""codigo de la prueba oficial del reto

Revision ID: 8111d774fcdd
Revises: 1060445ba064
Create Date: 2026-09-05 19:36:57.086821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8111d774fcdd'
down_revision: Union[str, Sequence[str], None] = '1060445ba064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prueba', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido_ejecutable', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prueba', schema=None) as batch_op:
        batch_op.drop_column('contenido_ejecutable')

    # ### end Alembic commands ###
