"""esquema del modelo de datos del MVP

Revision ID: b4e286913775
Revises: 
Create Date: 2026-09-05 13:05:35.344209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b4e286913775'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizacion',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('sitio_web', sa.String(length=500), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('momento_alta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_correo'), ['correo'], unique=True)

    op.create_table('evento_auditoria',
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('momento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('resultado', sa.String(length=16), nullable=False),
    sa.Column('origen', sa.String(length=16), nullable=False),
    sa.Column('referencia_recurso', sa.String(length=120), nullable=False),
    sa.Column('detalle_saneado', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evento_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evento_auditoria_accion'), ['accion'], unique=False)
        batch_op.create_index(batch_op.f('ix_evento_auditoria_momento'), ['momento'], unique=False)

    op.create_table('perfil_estudiante',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_publico', sa.String(length=255), nullable=False),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('visibilidad', sa.String(length=16), nullable=False),
    sa.Column('universidad', sa.String(length=255), nullable=True),
    sa.Column('carrera', sa.String(length=255), nullable=True),
    sa.Column('ciclo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('representacion',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('organizacion_id', sa.Uuid(), nullable=False),
    sa.Column('funcion_autorizada', sa.String(length=24), nullable=False),
    sa.Column('momento_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('momento_fin', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'organizacion_id')
    )
    op.create_table('solicitud_reto',
    sa.Column('representante_usuario_id', sa.Uuid(), nullable=False),
    sa.Column('organizacion_id', sa.Uuid(), nullable=False),
    sa.Column('titulo_original', sa.String(length=500), nullable=False),
    sa.Column('contenido_original_restringido', sa.Text(), nullable=True),
    sa.Column('momento_recepcion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado_preparacion', sa.String(length=16), nullable=False),
    sa.Column('modelo_ia', sa.String(length=120), nullable=True),
    sa.Column('version_instrucciones', sa.String(length=40), nullable=True),
    sa.Column('resumen_preparacion', sa.Text(), nullable=True),
    sa.Column('detalle_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['representante_usuario_id', 'organizacion_id'], ['representacion.usuario_id', 'representacion.organizacion_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reto',
    sa.Column('organizacion_id', sa.Uuid(), nullable=False),
    sa.Column('solicitud_id', sa.Uuid(), nullable=True),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('descripcion_publica', sa.Text(), nullable=False),
    sa.Column('criterios_aceptacion', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('momento_publicacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('momento_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repositorio_base', sa.String(length=500), nullable=True),
    sa.Column('version_base', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud_reto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participacion',
    sa.Column('perfil_usuario_id', sa.Uuid(), nullable=False),
    sa.Column('reto_id', sa.Uuid(), nullable=False),
    sa.Column('momento_incorporacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_usuario_id'], ['perfil_estudiante.usuario_id'], ),
    sa.ForeignKeyConstraint(['reto_id'], ['reto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perfil_usuario_id', 'reto_id', name='uq_participacion_perfil_reto')
    )
    op.create_table('prueba',
    sa.Column('reto_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('categoria', sa.String(length=16), nullable=False),
    sa.Column('obligatoria', sa.Boolean(), nullable=False),
    sa.Column('condicion_aprobacion', sa.Text(), nullable=False),
    sa.Column('limite_ejecucion_ms', sa.Integer(), nullable=True),
    sa.Column('referencia_ejecutable', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['reto_id'], ['reto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrega',
    sa.Column('participacion_id', sa.Uuid(), nullable=False),
    sa.Column('numero_intento', sa.Integer(), nullable=False),
    sa.Column('momento_entrega', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repositorio', sa.String(length=500), nullable=False),
    sa.Column('commit', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['participacion_id'], ['participacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participacion_id', 'numero_intento', name='uq_entrega_intento')
    )
    op.create_table('evaluacion',
    sa.Column('entrega_id', sa.Uuid(), nullable=False),
    sa.Column('estado_procesamiento', sa.String(length=16), nullable=False),
    sa.Column('momento_solicitud', sa.DateTime(timezone=True), nullable=False),
    sa.Column('momento_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('momento_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_evaluador', sa.String(length=60), nullable=False),
    sa.Column('dictamen', sa.String(length=16), nullable=True),
    sa.Column('detalle_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entrega_id'], ['entrega.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credencial',
    sa.Column('participacion_id', sa.Uuid(), nullable=False),
    sa.Column('evaluacion_id', sa.Uuid(), nullable=False),
    sa.Column('identificador_publico', sa.String(length=40), nullable=False),
    sa.Column('momento_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contenido_emitido', sa.Text(), nullable=False),
    sa.Column('huella_contenido', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluacion.id'], ),
    sa.ForeignKeyConstraint(['participacion_id'], ['participacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluacion_id')
    )
    with op.batch_alter_table('credencial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credencial_identificador_publico'), ['identificador_publico'], unique=True)

    op.create_table('resultado_prueba',
    sa.Column('evaluacion_id', sa.Uuid(), nullable=False),
    sa.Column('prueba_id', sa.Uuid(), nullable=False),
    sa.Column('condicion_ejecucion', sa.String(length=16), nullable=False),
    sa.Column('aprobada', sa.Boolean(), nullable=True),
    sa.Column('valor_observado', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unidad', sa.String(length=24), nullable=True),
    sa.Column('duracion_ms', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluacion.id'], ),
    sa.ForeignKeyConstraint(['prueba_id'], ['prueba.id'], ),
    sa.PrimaryKeyConstraint('evaluacion_id', 'prueba_id')
    )
    op.create_table('revocacion_credencial',
    sa.Column('credencial_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('momento_revocacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['credencial_id'], ['credencial.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('credencial_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revocacion_credencial')
    op.drop_table('resultado_prueba')
    with op.batch_alter_table('credencial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credencial_identificador_publico'))

    op.drop_table('credencial')
    op.drop_table('evaluacion')
    op.drop_table('entrega')
    op.drop_table('prueba')
    op.drop_table('participacion')
    op.drop_table('reto')
    op.drop_table('solicitud_reto')
    op.drop_table('representacion')
    op.drop_table('perfil_estudiante')
    with op.batch_alter_table('evento_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_auditoria_momento'))
        batch_op.drop_index(batch_op.f('ix_evento_auditoria_accion'))

    op.drop_table('evento_auditoria')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_correo'))

    op.drop_table('usuario')
    op.drop_table('organizacion')
    # ### end Alembic commands ###
