export const RETOS = [
  {
    id: 'CS-ENG-9042',
    titulo: 'Motor de Ingestión de Métricas en Alta Concurrencia',
    org: 'CloudScale Systems',
    orgIniciales: 'CS',
    stack: ['Rust', 'Kafka', 'ClickHouse'],
    dificultad: 'HARD',
    puntos: 120,
    estado: 'abierto',
    metrics: '>1000 req/s · p95 < 50 ms · memory < 256MB',
  },
  {
    id: 'FQ-CORE-7719',
    titulo: 'Optimización de Concurrencia en Ledger Distribuido',
    org: 'FinTech Quantum',
    orgIniciales: 'FQ',
    stack: ['Go', 'PostgreSQL', 'Redis', 'gRPC'],
    dificultad: 'EXPERT',
    puntos: 200,
    estado: 'abierto',
    metrics: '>2500 tx/s · p99 < 80 ms · 0% packet loss',
  },
  {
    id: 'DF-PIPE-3310',
    titulo: 'Pipeline ETL Reactivo con Backpressure Dinámico',
    org: 'DataFlow Labs',
    orgIniciales: 'DF',
    stack: ['Python', 'Apache Flink', 'AWS S3'],
    dificultad: 'MEDIUM',
    puntos: 85,
    estado: 'abierto',
    metrics: '>10000 events/s · lag < 200 ms · auto-recovery',
  },
  {
    id: 'HM-L7-8821',
    titulo: 'Proxy Reverso L7 con Detección de Anomalías',
    org: 'HyperMesh Networks',
    orgIniciales: 'HM',
    stack: ['C++', 'eBPF', 'Envoy'],
    dificultad: 'HARD',
    puntos: 150,
    estado: 'cerrado',
    metrics: '>1000 req/s · p95 < 50 ms · 99.99% uptime',
  },
  {
    id: 'NB-RATELIM-505',
    titulo: 'Algoritmo de Rate Limiting Adaptativo Distribuido',
    org: 'NeoBank Core',
    orgIniciales: 'NB',
    stack: ['Elixir', 'Redis Cluster', 'Docker'],
    dificultad: 'MEDIUM',
    puntos: 95,
    estado: 'abierto',
    metrics: '>5000 req/s · jitter < 5 ms · multi-region',
  },
  {
    id: 'AT-IOT-2204',
    titulo: 'Compresión de Series Temporales en Borde IoT',
    org: 'AeroTelemetry Global',
    orgIniciales: 'AT',
    stack: ['Zig', 'MQTT', 'TimescaleDB'],
    dificultad: 'MEDIUM',
    puntos: 70,
    estado: 'cerrado',
    metrics: 'ratio > 10:1 · ingestion p95 < 30 ms',
  },
];
